### ISSUE TITLE
Stop using core-resource-app!

### ISSUE THREAD

**Issue by varl** [dhis2/notes#26]
I did an experiment where I removed [`core-resource-app`](https://github.com/dhis2/core-resource-app) from my `apps-to-bundle.js` file in the backend, and I found that we have a majority of applications that do not use the core resources, instead bundling all of their dependencies.

### The contenders 🥇 

>N.B. The file sizes are noted for documentation purposes as a baseline, there is no comparison between apps with and without core-resources.
>
>All file sizes are taken from developer tools with cache disabled, and only measures: JS, CSS, Img, Media, Font, Documents, and Manifest requests.
>
>As such, XHR request data does not count to the size.

#### Apps that use core-resource (😞)

- https://dhis2.vardevs.se/dev/dhis-web-app-management/ (650 KB)
- https://dhis2.vardevs.se/dev/dhis-web-cache-cleaner/ (1022 KB)
- https://dhis2.vardevs.se/dev/dhis-web-dashboard/ (2.7 MB)
- https://dhis2.vardevs.se/dev/dhis-web-data-visualizer/#/ (949 KB)
- https://dhis2.vardevs.se/dev/dhis-web-event-capture/ (1.5 MB)
- https://dhis2.vardevs.se/dev/dhis-web-interpretation/ (3.1 MB)
- https://dhis2.vardevs.se/dev/dhis-web-maintenance/ (1.3 MB)
- https://dhis2.vardevs.se/dev/dhis-web-scheduler/#/ (692 KB)
- https://dhis2.vardevs.se/dev/dhis-web-tracker-capture/ (1.7 MB)
- https://dhis2.vardevs.se/dev/dhis-web-user/ (1.1 MB)

#### Apps that don't (⭐️)

- https://dhis2.vardevs.se/dev/dhis-web-capture/#/ (2.3 MB)
- https://dhis2.vardevs.se/dev/dhis-web-data-administration/#/ (204 KB)
- https://dhis2.vardevs.se/dev/dhis-web-visualizer/ (data viz classic) (890 KB)
- https://dhis2.vardevs.se/dev/dhis-web-data-quality/#/ (204 KB)
- https://dhis2.vardevs.se/dev/dhis-web-datastore/#/ (581 KB)
- https://dhis2.vardevs.se/dev/dhis-web-event-reports/ (782 KB)
- https://dhis2.vardevs.se/dev/dhis-web-mapping/ (1.0 MB)
- https://dhis2.vardevs.se/dev/dhis-web-maps/ (1.4 MB)
- https://dhis2.vardevs.se/dev/dhis-web-menu-management/ (474 KB)
- https://dhis2.vardevs.se/dev/dhis-web-messaging/#/PRIVATE (686 KB)
- https://dhis2.vardevs.se/dev/dhis-web-pivot/ (764 KB)
- https://dhis2.vardevs.se/dev/dhis-web-settings/#/general (812 KB)
- https://dhis2.vardevs.se/dev/dhis-web-translations/ (202 KB)
- https://dhis2.vardevs.se/dev/dhis-web-usage-analytics/ (298 KB)
- https://dhis2.vardevs.se/dev/dhis-web-user-profile/#/viewProfile (928 KB)

#### Apps that rebel and use an external CDN ... (💩)

- https://dhis2.vardevs.se/dev/dhis-web-importexport/#/ (868 KB) (_wtf? don't do this..._)

### The prize 🗽

- We save ~**137 MB** of bandwidth every time the backend builds
- We save ~**25 MB** on the compressed `dhis.war` archive
- We can [simplify](https://github.com/dhis2/dashboards-app/blob/master/config/webpack.config.prod.js#L267-L270) [our](https://github.com/dhis2/maintenance-app/blob/master/webpack.config.js#L77-L95) [webpack](https://github.com/dhis2/messaging-app/blob/master/webpack.dev.js#L37-L38) configurations by stripping out `externals` and `vendorScripts` (mostly).
- We get more predictable behaviour between development and production builds, through less edge cases and less difference between dev/prod configurations.

### Call to Action 💪 

- Bundle your dependencies!
- Chunk the dependencies to a different bundle file than your app!
- Simplify your Webpack configs!

### TODO

- [x] scheduler - [PR](https://github.com/dhis2/scheduler-app/pull/19)
- [x] app management - [PR](https://github.com/dhis2/app-management-app/pull/48)
- [x] user - [PR](https://github.com/dhis2/user-app/pull/51)
- [x] maintenance - [PR](https://github.com/dhis2/maintenance-app/pull/640)
- [x] import-export - [PR](https://github.com/dhis2/import-export-app/pull/22)
- [x] cache cleaner -[PR](https://github.com/dhis2/cache-cleaner-app/pull/32)
- [x] interpretation - [PR](https://github.com/dhis2/interpretation-app/pull/12)
- [x] dashboards - [PR](https://github.com/dhis2/dashboards-app/pull/263)
- [x] data visualizer [BRANCH](https://github.com/dhis2/data-visualizer-app/tree/epic/merge-dv-and-pt-apps-DHIS2-7687)
- [x] tracker capture - [PR](https://github.com/dhis2/tracker-capture-app/pull/402)
- [x] ~event capture~ - [PR](https://github.com/dhis2/dhis2-core/pull/3215)

### Caveats

- The measurements are made on a fresh load, and the idea is that the fake-CDN allows resources to be cached across apps, reducing the data loaded by subsequent apps. With bundled deps, every app needs to be loaded fully _once_ for the resources to be cached.

### JIRA link

https://jira.dhis2.org/browse/TECH-91

**Comment by varl** [comment]
A PR of [app-management](https://github.com/dhis2/app-management-app/pull/48) with no core-resources is up so we can look at the numbers:

- _Before:_ **650 KB**
- _After:_  **716 KB**

This only updates webpack/babel and as little of the code as possible. It does introduce **d2-i18n** ([runtime dep](https://bundlephobia.com/result?p=@dhis2/d2-i18n@1.0.4) that adds 10 KB minified/gzipped) and move away from the server-side translations.

There are additional savings that can be done:

- Upgrade it to React 16, so it's possible to pull in the new headerbar
- Switch imports to tree-shake friendly ones
- Update d2-ui components
- Add bundle chunking

**Comment by varl** [comment]
PR for [scheduler-app](https://github.com/dhis2/scheduler-app/pull/19) with no core-resources.

- _Before_: **692 KB**
- _After_: **450.25 KB**

**Comment by varl** [comment]
PR for [user-app](https://github.com/dhis2/user-app/pull/51/files) with no core-resources.

- _Before_: **1.1 MB**
- _After_: **817.45 KB**

**Comment by varl** [comment]
PR for [maintenance-app](https://github.com/dhis2/maintenance-app/pull/640) without core resources:

* _Before_: **1.3 MB**
* _After_: **1.23 MB**

**Comment by varl** [comment]
PR for [import-export-app](https://github.com/dhis2/import-export-app/pull/22) without core resources:

* _Before_: **868 KB**
* _After_: **996.92 KB**

**Comment by varl** [comment]
PR for [cache-cleaner-app](https://github.com/dhis2/cache-cleaner-app/pull/32) (_oh god it's Angular 1!_ 🤢 ) without core resources:

* _Before_: **1022 KB**
* _After_: **303.10 KB**

**Comment by varl** [comment]
PR for [interpretation-app](https://github.com/dhis2/interpretation-app/pull/12) without core resources:

* _Before_: **3.1 MB**
* _After_: **2.8 MB**

**Comment by varl** [comment]
Dashboards before and after:

- _Before_: **2.7 MB**
- _After_: **2.61 MB**

**Comment by varl** [comment]
Event Capture has been deprecated in 2.32. :tada:

**Comment by varl** [comment]
Looks like all external resources have been removed in the App Platform port of Data Visualizer: https://github.com/dhis2/data-visualizer-app/tree/epic/merge-dv-and-pt-apps-DHIS2-7687

**Comment by varl** [comment]
Two more PRs to merge and then we are golden. :medal_sports:
